import React, { useEffect, useRef, useState } from "react";
import sdk from "@stackblitz/sdk";
import { ClipLoader } from "react-spinners";

const LivePreview = ({ code, framework }) => {
  const wrapperRef = useRef(null);
  const [isLoading, setIsLoading] = useState(true);

  // Clean Markdown wraps off the code generated by the AI
  const cleanCode = (rawCode) => {
    if (!rawCode) return "";
    return rawCode.replace(/```(?:jsx|javascript|typescript|html|css|vue|angular|tsx|ts)?/g, "").trim();
  };

  useEffect(() => {
    if (!wrapperRef.current || !code) return;

    let active = true;
    setIsLoading(true);

    // 1. Clear any previous iframe or elements inside the stable wrapper
    wrapperRef.current.innerHTML = "";

    // 2. Create a fresh child div to pass to StackBlitz (since StackBlitz replaces the target element)
    const embedDiv = document.createElement("div");
    embedDiv.style.width = "100%";
    embedDiv.style.height = "100%";
    wrapperRef.current.appendChild(embedDiv);

    const cleanedCode = cleanCode(code);
    let template = "vanilla-js";
    let files = {};

    switch (framework) {
      case "react-js":
      case "react-tailwind":
      case "react-bootstrap":
      case "next-js": // Preview Next.js pages using create-react-app template for high performance
        template = "create-react-app";
        files = {
          "package.json": JSON.stringify({
            name: "ai-react-component",
            dependencies: {
              react: "^18.2.0",
              "react-dom": "^18.2.0",
              "react-icons": "^5.2.0",
              "lucide-react": "^0.395.0",
              "framer-motion": "^10.16.4"
            },
          }, null, 2),
          "public/index.html": `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>React Preview</title>
  ${framework.includes('tailwind') || framework === 'next-js' ? '<script src="https://cdn.tailwindcss.com"></script>' : ''}
  ${framework.includes('bootstrap') ? '<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">' : ''}
</head>
<body style="margin: 0; background: #0e0e11; color: #fff; font-family: sans-serif;">
  <div id="root"></div>
</body>
</html>
          `,
          "src/index.js": `
import React from "react";
import ReactDOM from "react-dom/client";
import App from "./App";
import "./style.css";

const root = ReactDOM.createRoot(document.getElementById("root"));
root.render(<App />);
          `,
          "src/style.css": `
            /* Custom Scrollbar */
            ::-webkit-scrollbar {
              width: 8px;
              height: 8px;
            }
            ::-webkit-scrollbar-track {
              background: #0e0e11;
            }
            ::-webkit-scrollbar-thumb {
              background: #333;
              border-radius: 4px;
            }
          `,
          "src/App.js": cleanedCode,
        };
        break;

      case "angular":
        template = "angular-cli";
        files = {
          "package.json": JSON.stringify({
            dependencies: {
              "@angular/common": "^15.0.0",
              "@angular/compiler": "^15.0.0",
              "@angular/core": "^15.0.0",
              "@angular/forms": "^15.0.0",
              "@angular/platform-browser": "^15.0.0",
              "@angular/platform-browser-dynamic": "^15.0.0",
              "rxjs": "^7.5.0",
              "tslib": "^2.3.0",
              "zone.js": "~0.12.0"
            }
          }, null, 2),
          "src/index.html": "<app-root>Loading component...</app-root>",
          "src/main.ts": `
import "zone.js";
import { platformBrowserDynamic } from "@angular/platform-browser-dynamic";
import { AppModule } from "./app/app.module";

platformBrowserDynamic().bootstrapModule(AppModule)
  .catch(err => console.error(err));
          `,
          "src/app/app.module.ts": `
import { NgModule } from "@angular/core";
import { BrowserModule } from "@angular/platform-browser";
import { AppComponent } from "./app.component";

@NgModule({
  declarations: [AppComponent],
  imports: [BrowserModule],
  bootstrap: [AppComponent]
})
export class AppModule {}
          `,
          "src/app/app.component.ts": cleanedCode,
        };
        break;

      case "vue":
        template = "vue";
        files = {
          "package.json": JSON.stringify({
            dependencies: {
              vue: "^3.2.0"
            }
          }, null, 2),
          "src/main.js": `
import { createApp } from 'vue';
import App from './App.vue';
createApp(App).mount('#app');
          `,
          "src/App.vue": cleanedCode,
          "index.html": `
<div id="app"></div>
<script type="module" src="/src/main.js"></script>
          `
        };
        break;

      default:
        template = "vanilla-js";
        files = {
          "index.html": cleanedCode
        };
        break;
    }

    // Embed project inside our dynamically appended embedDiv
    sdk.embedProject(embedDiv, {
      title: `${framework.toUpperCase()} Component Preview`,
      description: "Live component generated by AI",
      template: template,
      files: files
    }, {
      view: "preview",
      height: "100%",
      width: "100%",
      hideNavigation: true,
      hideDevTools: true,
      theme: "dark",
      clickToLoad: false,
    }).then(() => {
      if (active) setIsLoading(false);
    }).catch(err => {
      if (active) {
        console.error("StackBlitz embed error:", err);
        setIsLoading(false);
      }
    });

    return () => {
      active = false;
    };

  }, [code, framework]);

  return (
    <div className="relative w-full h-full flex flex-col" style={{ minHeight: "550px" }}>
      {isLoading && (
        <div className="absolute inset-0 bg-[#141319] flex flex-col items-center justify-center z-20 gap-4">
          <ClipLoader color="#3b82f6" size={40} />
          <p className="text-gray-400 text-sm animate-pulse">Building live preview environment...</p>
        </div>
      )}
      <div ref={wrapperRef} className="w-full flex-grow border-none overflow-hidden" style={{ minHeight: "550px" }} />
    </div>
  );
};

export default LivePreview;
